"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.unregister = exports.register = exports.ReactPwa = exports.usePwa = void 0;
var context_1 = require("./context");
Object.defineProperty(exports, "usePwa", { enumerable: true, get: function () { return context_1.usePwa; } });
var provider_1 = require("./provider");
Object.defineProperty(exports, "ReactPwa", { enumerable: true, get: function () { return provider_1.ReactPwa; } });
var sw_config_1 = require("./sw.config");
Object.defineProperty(exports, "register", { enumerable: true, get: function () { return sw_config_1.register; } });
Object.defineProperty(exports, "unregister", { enumerable: true, get: function () { return sw_config_1.unregister; } });
